header:
  schema-version: 2.0.0
  last-updated: '2025-01-01'
  last-reviewed: '2025-01-01'
  url: https://github.com/od10ventures/pvtr/.github/security-insights.yml
  comment: |
    This file contains the security insights information for the Meshery project.
project:
  name: meshery
  administrators:
    - name: Sangram Rath 
      affiliation: Meshery
      email: sangram@od10.in
      primary: true
  documentation:
    quickstart-guide: https://github.com/od10ventures/pvtr/blob/master/README.md
    detailed-guide: https://github.com/od10ventures/pvtr/blob/master/README.md
    code-of-conduct: https://github.com/od10ventures/pvtr/blob/master/CODE_OF_CONDUCT.md
  repositories:
    - name: website
      url: https://github.com/od10ventures/website
      comment: |
        Website.
    - name: odjobs
      url: https://github.com/od10ventures/odjobs
      comment: |
        odjobs.
    - name: 1ClickD
      url: https://github.com/od10ventures/1ClickD
      comment: |
        1ClickD.
    - name: web
      url: https://github.com/od10ventures/web
      comment: |
        web.
  vulnerability-reporting:
    reports-accepted: true
    bug-bounty-available: false
    contact:
      name: The security team at OD10 provides security support for this project.
      email: sangram@od10.in
      primary: true
    security-policy: https://github.com/od10ventures/pvtr/blob/master/SECURITY.md
